### ISSUE TITLE
Problem start deamon in docker 

### ISSUE THREAD

**Issue by ghost** [infiniband-radar/infiniband-radar-daemon#6]
**docker --version**
Docker version 17.09.1-ce

**docker logs sad_hermann**
ibwarn: [1] _do_madrpc: recv failed: Operation timed out
ibwarn: [1] mad_rpc: _do_madrpc failed; dport (DR path slid 0; dlid 0; 0)
Sending initial topology
ibwarn: [1] _do_madrpc: recv failed: Operation timed out
ibwarn: [1] mad_rpc: _do_madrpc failed; dport (DR path slid 0; dlid 0; 0)
curl_easy_perform() failed: Couldn't resolve host name
Assertion failed: res == CURLE_OK (/project/code/src/ApiClient.cpp: make_api_request: 77)

**/cofnig/config.1.json** 
```
{
  "api": {
    "entry_point": "https://fabric-radar-api-host.local/api",
    "token": "test-token",
    "fabric_id": "ib-test"
  },
  "ca_name": "mlx5_0",
  "ca_port": 1,
  "topology_update_interval_sec": 180,
  "port_stats_interval_sec": 5
}
```

**Comment by carstenpatzke** [comment]
Hey,
thank you for using the InfiniBand-Radar :).
You need to deploy the web interface first, see: https://github.com/infiniband-radar/infiniband-radar-web
This grants you access to the API.
You also need to modify the "entry_point" inside the json, just replace "fabric-radar-api-host.local" with the hostname of your web interface.

**Comment by ghost** [comment]
Hey,

thanks for you help do install InfiniBand-Radar  :-)

**Comment by carstenpatzke** [comment]
You're welcome.
Let me know if you have any further question and if it's even working for you.
