### ISSUE TITLE
libcurl.so.4: no version information

### ISSUE THREAD

**Issue by trothgsi** [infiniband-radar/infiniband-radar-daemon#9]
Hi,

when starting the daemon (installed from rpm) on a fresh CentOS 7.7 installation, it complains about the missing libcurl.so.4 version information:

`
~$ ldd /usr/sbin/infiniband_radar_daemon
/usr/sbin/infiniband_radar_daemon: /lib64/libcurl.so.4: no version information available (required by /usr/sbin/infiniband_radar_daemon)
...
`

Google says this is usually due to mixing versions of curl and libcurl (self compiled curl etc), but this is a fresh standard installation.

The issue is invariant under removal and reinstallation of all curl-packages.

Regards,
Thomas

**Comment by carstenpatzke** [comment]
Hey,

interesting, we have this message on our machines too, but we ignored it.

Do you have any problems with running the daemon?

**Comment by trothgsi** [comment]
Hi,

yes, this message actually shows up in `systemctl status infiniband-radar@gc.service`, which is in state "Failed":

`
infiniband_radar_daemon[12824]: /usr/sbin/infiniband_radar_daemon: /lib64/libcurl.so.4: no version information available (required by /usr/sbin/infiniband_radar_daemon)
infiniband_radar_daemon[12824]: Fail to parse config
`

_Fail to parse config_ could be something else, but it also shows up in `infiniband_radar_daemon /etc/infiniband-radar/config.gc.json` and as shown with `ldd`.

Wouldn't it be suprising if ldd shows a missing library and the executable still runs?

Cheers
Thomas

**Comment by FredH-ITER** [comment]
Hello,
Which solution did you find for /lib64/libcurl.so.4: no version information available?
edit: seems not a blocker
